ALTER TABLE users
ALTER COLUMN username TYPE TEXT,
ALTER COLUMN display_name TYPE TEXT;

ALTER TABLE users
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
ADD COLUMN IF NOT EXISTS games_played INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS wins INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS win_streak INTEGER NOT NULL DEFAULT 0;

CREATE UNIQUE INDEX IF NOT EXISTS idx_users_display_name_unique
ON users (display_name);
